import Head from 'next/head';
import Image from 'next/image';
import HeroBanner from '../components/utils/HeroBanner';
import Services from '../components/utils/Services';
import { BsFillTelephoneFill } from 'react-icons/bs';
export default function Home() {
	return (
		<div>
			<Head>
				<link rel='icon' href='/favicon.ico' />
				<link rel='manifest' href='/manifest.json' />
				<link rel='apple-touch-icon' href='/vercel.svg' />

				<title>JScrips Template</title>
				<meta name='description' content='Generated by create next app.' />
				<meta
					property='og:url'
					content='https://jscrips-website-starter.vercel.app/'
				/>
				<meta property='og:type' content='website' />
				<meta property='og:title' content='JScrips Template' />
				<meta
					property='og:description'
					content='Generated by create next app.'
				/>
				<meta
					property='og:image'
					content='https://jscrips-website-starter.vercel.app/vercel.svg'
				/>

				<meta name='twitter:card' content='summary_large_image' />
				<meta
					property='twitter:domain'
					content='jscrips-website-starter.vercel.app'
				/>
				<meta
					property='twitter:url'
					content='https://jscrips-website-starter.vercel.app/'
				/>
				<meta name='twitter:title' content='JScrips Template' />
				<meta
					name='twitter:description'
					content='Generated by create next app.'
				/>
				<meta
					name='twitter:image'
					content='https://jscrips-website-starter.vercel.app/vercel.svg'
				/>
			</Head>

			<HeroBanner>
				<div className='flex min-h-full flex-col items-center justify-center'>
					<h2 className='lg:9xl text-center text-3xl font-semibold md:text-7xl'>
						{' '}
						Main headline, put top keyword here
					</h2>
					<p className='mt-4 w-8/12 text-center text-sm tracking-tight md:text-lg lg:text-2xl'>
						{' '}
						Expand on the keyword with more keywords and add a list of related
						services that you do and include the city, state of your service
						area.
					</p>

					<div className='flex gap-10 pt-10'>
						<button
							className='rounded-lg bg-emerald-800 px-4 text-sm font-semibold md:px-8 md:text-lg lg:text-2xl'
							aria-label='About Us'>
							About Us
						</button>

						<div className='flex items-center gap-2'>
							<BsFillTelephoneFill className='text-xl md:text-4xl lg:text-4xl' />
							<div className='flex flex-col'>
								<span className='text-sm md:text-lg lg:text-xl'> CALL NOW</span>
								<span className='text-base font-bold md:text-lg lg:text-2xl'>
									555-555-5555
								</span>
							</div>
						</div>
					</div>
				</div>
			</HeroBanner>
			<Services />
		</div>
	);
}
